name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Bump version to Minor
        shell: ./bump.sh

      - name: Commit the version
        uses: EndBug/add-and-commit@v9
        with:
          message: Bump version to minor
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          add: |
            - pyproject.toml
            - setup.cfg