name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Bump version to Minor
        id: bump
        run: |
          NEW_VERSION=$(bash bump.sh)
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Version bumped to: $NEW_VERSION"

      - name: Commit the version
        uses: EndBug/add-and-commit@v9
        with:
          message: Bump version to ${{ steps.bump.outputs.new_version }}
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          add: |
            - pyproject.toml
            - setup.cfg

      - name: Create tag
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: v${{ steps.bump.outputs.new_version }}
          message: "Bump version to ${{ steps.bump.outputs.new_version }}"