name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest
    environment: GITHUB_TOKEN
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Check Dir
        run: ls -lha

      - name: Bump version to Minor
        id: bump
        run: |
          NEW_VERSION=$(bash bump.sh)
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Version bumped to: $NEW_VERSION"

      - name: Commit the version
        uses: EndBug/add-and-commit@v9
        with:
          message: Bump version to ${{ steps.bump.outputs.new_version }} [skip ci]
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          add: |
            - pyproject.toml
            - setup.cfg

      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.bump.outputs.new_version }}',
              sha: context.sha
            })
        